# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.20"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
        
    - name: Set up binary name 
      run: |
        BINARY_NAME=${{github.repository}}-$GOOS-$GOARCH
        echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_ENV
        echo "GOOS=$GOOS" >> $GITHUB_ENV
        echo "GOARCH=$GOARCH" >> $GITHUB_ENV

    - name: Install goimports
      run: |
        go install golang.org/x/tools/cmd/goimports@latest
        export PATH="$HOME/go/bin:$PATH"
        
    - name: Build
      working-directory: ./src
      run: go build -o "$BINARY_NAME" -v ./...

    - name: Test
      working-directory: ./src
      run: go test -v ./...

    - name: Format
      run: if [ "$(goimports -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
      if: matrix.go-version == 1.20
      
    - name: Release Notes
      run:
        git log $(git describe HEAD~ --tags --abbrev=0)..HEAD --pretty='format:* %h %s%n  * %an <%ae>' --no-merges >> ".github/RELEASE-TEMPLATE.md"
          
    - name: Release with Notes
      uses: softprops/action-gh-release@v1
      with:
        body_path: ".github/RELEASE-TEMPLATE.md"
        draft: true
        files: ./src/${{env.BINARY_NAME}}
        token: ${{ secrets.PERSONALTOKEN }}
