# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
    contents: write
    packages: write

env:
  GOVERSION: "1.20"
  
jobs:

  build:    
    strategy:
      fail-fast: false
      matrix:
        include:
          - { runner: macos-latest,  go-os: darwin,  go-arch: amd64, build-tags: netcgo }
          - { runner: macos-latest,  go-os: darwin,  go-arch: arm64, build-tags: netcgo }
          - { runner: ubuntu-latest, go-os: linux,   go-arch: amd64, }
          - { runner: ubuntu-latest, go-os: linux,   go-arch: arm64, }
          - { runner: windows-latest, go-os: windows, go-arch: amd64, build-env: CGO_ENABLED=1, suffix: .exe }

    runs-on: ${{ matrix.runner }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go ${{env.GOVERSION}}
      uses: actions/setup-go@v3
      with:
        go-version: ${{env.GOVERSION}}
        
      env: 
        BINARYNAME: ${{github.repository}}-${{matrix.go-os}}-${{matrix.go-arch}}${{matrix.suffix}}

    - name: Install goimports
      run: |
        go install golang.org/x/tools/cmd/goimports@latest
        export PATH="$HOME/go/bin:$PATH"
        
    - name: Build
      working-directory: ./src
      run: ${{ matrix.build-env }} GOOS=${{ matrix.go-os }} GOARCH=${{ matrix.go-arch }} go build -o "${{env.BINARYNAME}}" -tags="${{ matrix.build-tags }}" -v ./...

    - name: Test
      working-directory: ./src
      run: go test -v ./...

    - name: Format
      run: if [ "$(goimports -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
      if: ${{env.GOVERSION == 1.20}}
      
    - name: Release Notes
      run:
        git log $(git describe HEAD~ --tags --abbrev=0)..HEAD --pretty='format:* %h %s%n  * %an <%ae>' --no-merges >> ".github/RELEASE-TEMPLATE.md"
          
    - name: Release with Notes
      uses: softprops/action-gh-release@v2
      with:
        body_path: ".github/RELEASE-TEMPLATE.md"
        files: ./src/${{env.BINARYNAME}}
        tag_name: latest
